/*
 * Orus Language Project
 * ---------------------------------------------------------------------------
 * File: include/compiler/codegen/peephole.h
 * Author: Jordy Orel KONDA
 * Copyright (c) 2025 Jordy Orel KONDA
 * License: MIT License (see LICENSE file in the project root)
 * Description: Provides declarations for peephole optimization passes that compact
 *              and simplify generated bytecode.
 */

#ifndef PEEPHOLE_H
#define PEEPHOLE_H

#include "compiler/compiler.h"

// Peephole optimization algorithms for bytecode-level optimizations
// Applies local optimizations to small instruction windows

typedef struct PeepholeContext {
    int patterns_optimized;
    int instructions_eliminated;
    int load_move_fusions;
    int redundant_moves;
    int constant_propagations;
} PeepholeContext;

// Main peephole optimization function
bool apply_peephole_optimizations(CompilerContext* ctx);
void init_peephole_context(PeepholeContext* ctx);
void print_peephole_statistics(PeepholeContext* ctx);
const PeepholeContext* get_peephole_statistics(void);

#endif // PEEPHOLE_H