name: release

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILD_PROFILE: release

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version
        id: version
        run: |
          VERSION_FILE="include/public/version.h"
          MAJOR=$(grep -E "#define ORUS_VERSION_MAJOR" "$VERSION_FILE" | awk '{print $3}')
          MINOR=$(grep -E "#define ORUS_VERSION_MINOR" "$VERSION_FILE" | awk '{print $3}')
          PATCH=$(grep -E "#define ORUS_VERSION_PATCH" "$VERSION_FILE" | awk '{print $3}')
          VERSION="v${MAJOR}.${MINOR}.${PATCH}"
          echo "Repository version: ${VERSION}"
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Determine trigger type
        id: trigger
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/v* ]]; then
            echo "from_tag=true" >> "$GITHUB_OUTPUT"
          else
            echo "from_tag=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Validate tag matches version
        if: steps.trigger.outputs.from_tag == 'true'
        run: |
          TAG="${GITHUB_REF##*/}"
          VERSION="${{ steps.version.outputs.version }}"
          if [[ "$TAG" != "$VERSION" ]]; then
            echo "Tag $TAG does not match version macros ($VERSION)." >&2
            exit 1
          fi

      - name: Build release artifacts
        run: |
          make clean
          make release

      - name: Check for binary changes
        if: steps.trigger.outputs.from_tag == 'true'
        env:
          TAG_NAME: ${{ steps.version.outputs.version }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail

          shopt -s nullglob
          artifact_pattern="dist/orus-*.tar.gz"
          new_artifacts=(${artifact_pattern})
          shopt -u nullglob

          if [[ ${#new_artifacts[@]} -eq 0 ]]; then
            echo "No build artifacts found matching ${artifact_pattern}" >&2
            exit 1
          fi

          api_url="https://api.github.com/repos/${GH_REPO}/releases/latest"
          status=$(curl -sS -o latest.json -w "%{http_code}" -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" "$api_url")

          if [[ "$status" != "200" ]]; then
            echo "No previous release found (status ${status}); skipping binary comparison."
            rm -f latest.json
            exit 0
          fi

          prev_tag=$(jq -r '.tag_name' latest.json)
          if [[ "$prev_tag" == "$TAG_NAME" ]]; then
            echo "Latest release already uses tag ${TAG_NAME}; skipping binary comparison."
            rm -f latest.json
            exit 0
          fi

          declare -A previous_hashes
          while read -r asset_name && read -r asset_url; do
            tmp_file=$(mktemp)
            curl -sSL -H "Authorization: Bearer ${GH_TOKEN}" -o "$tmp_file" "$asset_url"
            previous_hashes["$asset_name"]=$(sha256sum "$tmp_file" | awk '{print $1}')
            rm -f "$tmp_file"
          done < <(jq -r '.assets[] | select(.name | test("^orus-.*\\.tar\\.gz$")) | .name + "\n" + .browser_download_url' latest.json)

          rm -f latest.json

          if [[ ${#previous_hashes[@]} -eq 0 ]]; then
            echo "Previous release has no matching artifacts; skipping binary comparison."
            exit 0
          fi

          changed_artifacts=0
          for artifact in "${new_artifacts[@]}"; do
            artifact_name=$(basename "$artifact")
            new_hash=$(sha256sum "$artifact" | awk '{print $1}')
            old_hash=${previous_hashes["$artifact_name"]:-}
            if [[ -z "$old_hash" ]]; then
              echo "No previous artifact named ${artifact_name}; treating as changed."
              changed_artifacts=$((changed_artifacts + 1))
              continue
            fi

            if [[ "$new_hash" != "$old_hash" ]]; then
              echo "Artifact ${artifact_name} changed (sha256 ${old_hash} -> ${new_hash})."
              changed_artifacts=$((changed_artifacts + 1))
            else
              echo "Artifact ${artifact_name} is unchanged compared to latest release." >&2
            fi
          done

          if [[ $changed_artifacts -eq 0 ]]; then
            echo "No release artifacts changed compared to latest release." >&2
            exit 1
          fi

      - name: Delete existing release (if any)
        if: steps.trigger.outputs.from_tag == 'true'
        env:
          TAG_NAME: ${{ steps.version.outputs.version }}
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          api_url="https://api.github.com/repos/${GH_REPO}/releases/tags/${TAG_NAME}"
          status=$(curl -sS -o response.json -w "%{http_code}" -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" "$api_url")
          if [[ "$status" == "200" ]]; then
            release_id=$(python -c "import json; import sys; data=json.load(open('response.json')); print(data.get('id',''))")
            if [[ -n "$release_id" ]]; then
              echo "Deleting existing release $release_id for ${TAG_NAME}"
              curl -sS -X DELETE -H "Authorization: Bearer ${GH_TOKEN}" -H "Accept: application/vnd.github+json" "https://api.github.com/repos/${GH_REPO}/releases/${release_id}" >/dev/null
            fi
          fi
          rm -f response.json

      - name: Create GitHub release
        if: steps.trigger.outputs.from_tag == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Orus ${{ steps.version.outputs.version }}
          generate_release_notes: true
          files: |
            dist/orus-*.tar.gz
          prerelease: false
          draft: false
          make_latest: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
